remote_theme: mmistakes/minimal-mistakes
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-include-cache

# Enable search
search: true
search_full_content: true
search_provider: lunr

title: "Sam Zheng's Blog"
description: "Thoughts on Philosophy, Neuroscience, and Math"
locale: "en-US"
author:
  name: "Zheyang (Sam) Zheng"
  bio: "PhD student in computational neuroscience at NYU"
  email: "samzhenguchi@gmail.com"
  location: "New York, NY"

# SEO settings
og_image: # Add path to an image for social media previews
twitter:
  username: # Add your Twitter handle if you have one

# Analytics (optional but helpful for tracking)
# google_analytics: # Add your GA tracking ID if you have one

markdown: kramdown
kramdown:
  math_engine: mathjax
  # Optional, but these lines enable $$ delimiters:
  math_engine_opts:
    inlinemath_delimiters: 
      - '$'
      - '$'
    displaymath_delimiters:
      - '$$'
      - '$$'
  syntax_highlighter_opts:
    disable_tables: true



defaults:
  - scope:
      path: "_posts"
      type: "posts"
    values:
      layout: "post"


url: "https://samdeoxys1.github.io"
baseurl: "/blog"

# # Optional but recommended
# paginate: 5
